language: java

cache:
  directories:
  - $HOME/.m2
jdk:
  - oraclejdk8
install:
  - cd ./wechat-spring-boot-autoconfigure
  - mvn clean install -Dmaven.test.skip=true --settings ../.m2/settings.xml -Ptravis-building
script:
  - mvn test --settings ../.m2/settings.xml -Ptravis-building
after_success:
  - mvn test -DactiveProfile=local jacoco:report coveralls:report --settings ../.m2/settings.xml -Ptravis-building
notifications:
  email:
    - heyuxian.me@gmail.com