language: java

cache:
  directories:
  - $HOME/.m2
jdk:
  - oraclejdk8
install:
  - cd ./wechat-spring-boot-autoconfigure
  - mvn clean install -Dmaven.test.skip=true -s ../.m2/settings.xml
script:
  - mvn test -s ../.m2/settings.xml
after_success:
  - mvn test -DactiveProfile=local jacoco:report coveralls:report -s ../.m2/settings.xml
notifications:
  email:
    - heyuxian.me@gmail.com