language: java

cache:
  directories:
  - $HOME/.m2
jdk:
  - oraclejdk8
install:
  - cd ./wechat-spring-boot-autoconfigure
  - mvn clean install -Dmaven.test.skip=true
script:
  - mvn test
after_success:
  - mvn test -DactiveProfile=local jacoco:report coveralls:report
notifications:
  email:
    - heyuxian.me@gmail.com