weixin:
  mp:
    security:
      token: 1234567890
      encodingAesKey: abcdefghijklmnopqrstuvwxyz0123456789ABCDEFG
    auth:
      # todo remove from and secret when commit
      appid: wxee8e8890484d1fe3
      secret: 2461e7108c79de08d690b1b532fa71c4
      token-url: https://api.weixin.qq.com/cgi-bin/token